#if !defined(SET_GLIBC_LINK_VERSIONS_HEADER) && !defined(__ASSEMBLER__)
#define SET_GLIBC_LINK_VERSIONS_HEADER
__asm__(".symver readdir,readdir@GLIBC_2.4");
__asm__(".symver strncmp,strncmp@GLIBC_2.4");
__asm__(".symver closedir,closedir@GLIBC_2.4");
__asm__(".symver strncpy,strncpy@GLIBC_2.4");
__asm__(".symver __stack_chk_fail,__stack_chk_fail@GLIBC_2.4");
__asm__(".symver strtok,strtok@GLIBC_2.4");
__asm__(".symver fgets,fgets@GLIBC_2.4");
__asm__(".symver strlen,strlen@GLIBC_2.4");
__asm__(".symver strstr,strstr@GLIBC_2.4");
__asm__(".symver confstr,confstr@GLIBC_2.4");
__asm__(".symver memcmp,memcmp@GLIBC_2.4");
__asm__(".symver environ,environ@GLIBC_2.4");
__asm__(".symver asprintf,asprintf@GLIBC_2.4");
__asm__(".symver opendir,opendir@GLIBC_2.4");
__asm__(".symver __environ,__environ@GLIBC_2.4");
__asm__(".symver getenv,getenv@GLIBC_2.4");
__asm__(".symver stderr,stderr@GLIBC_2.4");
__asm__(".symver fwrite,fwrite@GLIBC_2.4");
__asm__(".symver fread,fread@GLIBC_2.4");
__asm__(".symver waitpid,waitpid@GLIBC_2.4");
__asm__(".symver strchr,strchr@GLIBC_2.4");
__asm__(".symver fprintf,fprintf@GLIBC_2.4");
__asm__(".symver __cxa_finalize,__cxa_finalize@GLIBC_2.4");
__asm__(".symver strcmp,strcmp@GLIBC_2.4");
__asm__(".symver strerror,strerror@GLIBC_2.4");
__asm__(".symver basename,basename@GLIBC_2.4");
__asm__(".symver snprintf,snprintf@GLIBC_2.4");
__asm__(".symver dlsym,dlsym@GLIBC_2.4");
__asm__(".symver waitpid,waitpid@GLIBC_2.4");
#endif
